### PR TITLE
FEAT: Added CrawlerDetect

### PR DESCRIPTION
**Pull request by juliangarcess**
Added crawler detect for prevent visit be created from knows crawlers.

### CODE REVIEW

**Comment by ousid** [comment]
It seems there's an error related to the allowed plugins once again, let me solve this tomorrow, and I'll re-check this again.

Thanks, @juliangarcess!

**Comment by juliangarcess** [comment]
I thin'k now is fixed

**Comment by ousid** [comment]
It seems all tests passed @juliangarcess.

Thanks!

**Comment by juliangarcess** [comment]
perfect, when I can use with composer?

**Comment by juliangarcess** [comment]
When the package will be updated at Packagist?

**Comment by ousid** [comment]
It got updated, you can upgrade now!

**Pull request merged**
