### PR TITLE
FEAT: Added with session function

### PR DESCRIPTION
**Pull request by juliangarcess**
Added with session function for base visits on session id

### CODE REVIEW

**Comment by ousid** [comment]
Hey, @juliangarcess 

Could you update the README file with your new method?

Thanks!

**Comment by juliangarcess** [comment]
Done!!

**Comment by ousid** [comment]
Thanks, Julian!

BTW, Could you explain a bit why we need such a method? AKA: the use cases?

**Comment by juliangarcess** [comment]
Cause when using a proxy like cloudflare something it makes hard to get visitor real IP

**Comment by ousid** [comment]
Thanks for the clarification

**Comment by juliangarcess** [comment]
and it can be interesting for intranet

**Pull request merged**
